CC=gcc
TARGET=libinterceptgl.so
SOURCE=./interceptgl.c ./util.c ./perf_util.c

CFLAGS=-I$(PFM_PATH)/libpfm4/perf_examples/ -I$(PFM_PATH)/libpfm4/include/ -I$(PFM_PATH)/pfm_multi/ -I./ -fPIC -shared
LDFLAGS=-L$(PFM_PATH)/libpfm4/lib/
LIBS=-lpfm -lpthread -lrt 


all: ${TARGET}

${TARGET}:${SOURCE}
	$(CC) $(LDFLAGS) $(CFLAGS) $^ -o $@ $(LIBS)

.PHONY:
clean:
	rm ${TARGET}
